### ISSUE TITLE
TransKey Docs

### ISSUE THREAD

**Issue by MincoMK** [Not-swasd/HCS-tool#6]
TransKey는 어디서 뜯은 건가요? 공식 mTransKey.js 에서 가져온 건가요?

**Comment by Not-swasd** [comment]
transkey.js 내 라인 13, 라인 560~564은 (hcs.js)[https://github.com/kimcore/hcs.js]의 (buildRaon.ts)[https://github.com/kimcore/hcs.js/blob/main/src/util/buildRaon.ts]를 참고하였고,  다른 함수나 클래스 등은 transkey 공식 파일(https://rl6cz18qh.toastcdn.net/eduro/*/raon/*)에서 가져와 코드 정리, 수정을 거친 겁니다.
